@startuml
!include functions.iuml
skinparam linetype ortho
hide empty members
hide circle
legend top left
Type : Entity Relationship Diagram
Name : PHP With Jacob Entities
Author : Glen Gerber
Creation Date : Wednesday, February 19, 2020
endlegend
package "MySQL server" <<rectangle>> {
package "test" <<database>> {
	table("Person") {
		*primaryKey("personId", "bigint")
		--
		*column("firstName", "varchar_30")
		column("middleName", "varchar_30")
		column("lastName", "varchar_30")
		column("gender", "varchar_1")
		column("birthDate", "timestamp")
	}
	table("Event") {
		*primaryKey("eventId", "bigint")
		--
		*foreignKey("eventTypeId", "bigint")
		*column("occuredOn", "date")
	}
	table("EventType") {
		*primaryKey("eventTypeId", "bigint")
		--
		column("shortCode", "varchar_3")
		column("description", "varchar_50")
	}
	note left of EventType
	  Birthday, Marriage,
	  Graduation, etc.
	end note
	table("PersonEvents") {
		*primaryAndForeignKey("personId", "bigint")
		*primaryAndForeignKey("eventId", "bigint")
		--
		column("details", "varchar_max")
	}
	table("PersonRelationships") {
		*primaryAndForeignKey("personId", "bigint")
		*primaryAndForeignKey("relationshipTypeId", "bigint")
		*primaryAndForeignKey("relatedPersonId", "bigint")
		--
		column("details", "varchar_max")
	}
	table("RelationshipType") {
		primaryKey("relationshipTypeId", "bigint")
		--
		column("shortCode", "varchar_3")
		column("description", "varchar_30")
	}
	note right of RelationshipType
	  Father, Mother
	end note
}
}
Event ||--|| EventType : fk_e_et_eventTypeId
Person ||..o{ PersonEvents : fk_pe_p_personId
PersonEvents }o..|| Event : fk_pe_e_eventId
PersonRelationships }|--|| RelationshipType : fk_pr_rt_relationshipTypeId
Person ||--|{ PersonRelationships : fk_pr_p_personId
Person ||--|{ PersonRelationships : fk_pr_p_relatedPersonId
@enduml